set PRIVATE_CLASSPATH=lib\commons-configuration-20041012.002804.jar
set PRIVATE_CLASSPATH=%PRIVATE_CLASSPATH%;lib\laf-plugin-7.1.jar
set PRIVATE_CLASSPATH=%PRIVATE_CLASSPATH%;lib\laf-widget-7.1.jar
set PRIVATE_CLASSPATH=%PRIVATE_CLASSPATH%;lib\logback-classic-1.0.4.jar
set PRIVATE_CLASSPATH=%PRIVATE_CLASSPATH%;lib\logback-core-1.0.4.jar
set PRIVATE_CLASSPATH=%PRIVATE_CLASSPATH%;lib\slf4j-api-1.6.4.jar
set PRIVATE_CLASSPATH=%PRIVATE_CLASSPATH%;lib\substance-7.1.jar
set PRIVATE_CLASSPATH=%PRIVATE_CLASSPATH%;lib\substance-swingx-7.1.jar
set PRIVATE_CLASSPATH=%PRIVATE_CLASSPATH%;lib\swingx-all-1.6.3.jar
set PRIVATE_CLASSPATH=%PRIVATE_CLASSPATH%;lib\swingx-core-1.6.2.jar
set PRIVATE_CLASSPATH=%PRIVATE_CLASSPATH%;lib\trident-7.1-swing.jar
set PRIVATE_CLASSPATH=%PRIVATE_CLASSPATH%;lib\derby-10.6.2.1.jar
set PRIVATE_CLASSPATH=%PRIVATE_CLASSPATH%;lib\miglayout-3.7.3.1.jar
set PRIVATE_CLASSPATH=%PRIVATE_CLASSPATH%;lib\RAccount-1.2.jar
@rem echo %PRIVATE_CLASSPATH% 
