set PRIVATE_CLASSPATH=lib\commons-configuration-20041012.002804.jar
set PRIVATE_CLASSPATH=%PRIVATE_CLASSPATH%;lib\commons-logging-1.1.1.jar
set PRIVATE_CLASSPATH=%PRIVATE_CLASSPATH%;lib\commons-logging-api-1.1.jar
set PRIVATE_CLASSPATH=%PRIVATE_CLASSPATH%;lib\derby-10.6.2.1.jar
set PRIVATE_CLASSPATH=%PRIVATE_CLASSPATH%;lib\miglayout-3.7.3.1.jar
set PRIVATE_CLASSPATH=%PRIVATE_CLASSPATH%;lib\RAccount-1.1.jar
@rem echo %PRIVATE_CLASSPATH% 
