package es.rchavarria.raccount.frontend.script;

import java.sql.SQLException;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import es.rchavarria.raccount.db.Session;

public class CreateTables {
    private static final Log log = LogFactory.getLog(CreateTables.class);
	private Session session;

    public CreateTables(Session session){
    	this.session = session;
    }

    public void execute() throws SQLException{
        createConceptTable(session);
        createAccountTable(session);
        createMovementsTable(session);
    }
    
    private void createMovementsTable(Session session) throws SQLException {
        String sqlCreateTableMovements = 
                "CREATE TABLE Movement ( " +
                "idMovement BIGINT GENERATED BY DEFAULT AS IDENTITY CONSTRAINT idMovement_PK PRIMARY KEY, " +
                "idAccount BIGINT NOT NULL, " +
                "idConcept BIGINT NOT NULL, " +
                "MovementDate DATE NOT NULL, " +
                "Description VARCHAR(256) NOT NULL, " +
                "Amount DOUBLE NOT NULL, " +
                "FinalBalance DOUBLE NOT NULL" +
                ")";
        session.sqlExecute(sqlCreateTableMovements);
        String sqlCreateMovementsIndex = 
            "CREATE UNIQUE INDEX Movement_IDX ON Movement(idMovement)";
        session.sqlExecute(sqlCreateMovementsIndex);
        String sqlAccountFK = 
            "ALTER TABLE Movement ADD CONSTRAINT Account_FK FOREIGN KEY (idAccount) REFERENCES Account(idAccount)";
        session.sqlExecute(sqlAccountFK);
        String sqlConceptFK = 
            "ALTER TABLE Movement ADD CONSTRAINT Concept_FK FOREIGN KEY (idConcept) REFERENCES Concept(idConcept)";
        session.sqlExecute(sqlConceptFK);

        log.info("Table Movement: created");
    }

    private void createConceptTable(Session session) throws SQLException {
        String sqlCreateTableConcept = 
                "CREATE TABLE Concept ( " +
                "idConcept BIGINT GENERATED BY DEFAULT AS IDENTITY CONSTRAINT idConcept_PK PRIMARY KEY, " +
                "Name VARCHAR(256) NOT NULL, " +
                "Visible SMALLINT NOT NULL" +
                ")";
        session.sqlExecute(sqlCreateTableConcept);
        String sqlCreateConceptIndex = 
            "CREATE UNIQUE INDEX Concept_IDX ON Concept(idConcept)";
        session.sqlExecute(sqlCreateConceptIndex);
        log.info("Table Concept: created");
    }

    private void createAccountTable(Session session) throws SQLException {
        String sqlCreateTableAccount = 
                "CREATE TABLE Account ( " +
                "idAccount BIGINT GENERATED BY DEFAULT AS IDENTITY CONSTRAINT idAccount_PK PRIMARY KEY, " +
                "Name VARCHAR(256) NOT NULL, " +
                "Balance DOUBLE NOT NULL, " +
                "Accountable SMALLINT NOT NULL, " +
                "CodeNumber VARCHAR(256)" +
                ")";
        session.sqlExecute(sqlCreateTableAccount);
        String sqlCreateAccountIndex = 
            "CREATE UNIQUE INDEX Account_IDX ON Account(idAccount)";
        session.sqlExecute(sqlCreateAccountIndex);
        log.info("Table Account: created");
    }

}
